--- 
- hosts: 127.0.0.1
  vars_files: 
    - ./var.yml
  tasks: 
    - name: deploy nsx manager1
      command: ovftool 
        --name={{m1.name}}
        --X:injectOvfEnv 
        --X:logFile=ovftool.log
        --allowExtraConfig 
        --datastore={{common.datastore}}
        --network="home_mgmt" 
        --acceptAllEulas 
        --noSSLVerify 
        --diskMode=thin 
        --powerOn 
        --prop:nsx_role="{{common.role}}"
        --prop:nsx_ip_0={{m1.ip}}
        --prop:nsx_netmask_0={{common.mask}}
        --prop:nsx_gateway_0={{common.gw}} 
        --prop:nsx_dns1_0={{common.dns}} 
        --prop:nsx_domain_0=rkc.local 
        --prop:nsx_ntp_0={{common.ntp}} 
        --prop:nsx_isSSHEnabled=True 
        --prop:nsx_allowSSHRootLogin=True
        --prop:nsx_passwd_0={{common.password}} 
        --prop:nsx_cli_passwd_0={{common.password}} 
        --prop:nsx_hostname={{m1.name}}
        --prop:nsx_cli_audit_passwd_0={{common.password}}
        "{{common.image}}"
        vi://"administrator@rkc.local":"Nicira123$"@vc.rkc.local/Home/host/cluster67
      tags: mgr

    - name: depploy nsx manager2
      command: ovftool
        --name={{m2.name}}
        --X:injectOvfEnv
        --X:logFile=ovftool.log
        --allowExtraConfig
        --datastore={{common.datastore}}
        --network="home_mgmt"
        --acceptAllEulas
        --noSSLVerify
        --diskMode=thin
        --powerOn
        --prop:nsx_role="{{common.role}}"
        --prop:nsx_ip_0={{m2.ip}}
        --prop:nsx_netmask_0={{common.mask}}
        --prop:nsx_gateway_0={{common.gw}}
        --prop:nsx_dns1_0={{common.dns}}
        --prop:nsx_domain_0=rkc.local
        --prop:nsx_ntp_0={{common.ntp}}
        --prop:nsx_isSSHEnabled=True
        --prop:nsx_allowSSHRootLogin=True
        --prop:nsx_passwd_0={{common.password}}
        --prop:nsx_cli_passwd_0={{common.password}}
        --prop:nsx_hostname={{m2.name}}
        --prop:nsx_cli_audit_passwd_0={{common.password}}
        "{{common.image}}"
        vi://"administrator@rkc.local":"Nicira123$"@vc.rkc.local/Home/host/cluster67
      tags: mgr2

    - name: deploy nsx manager3
      command: ovftool
        --name={{m3.name}}
        --X:injectOvfEnv
        --X:logFile=ovftool.log
        --allowExtraConfig
        --datastore={{common.datastore}}
        --network="home_mgmt"
        --acceptAllEulas
        --noSSLVerify
        --diskMode=thin
        --powerOn
        --prop:nsx_role="{{common.role}}"
        --prop:nsx_ip_0={{m3.ip}}
        --prop:nsx_netmask_0={{common.mask}}
        --prop:nsx_gateway_0={{common.gw}}
        --prop:nsx_dns1_0={{common.dns}}
        --prop:nsx_domain_0=rkc.local
        --prop:nsx_ntp_0={{common.ntp}}
        --prop:nsx_isSSHEnabled=True
        --prop:nsx_allowSSHRootLogin=True
        --prop:nsx_passwd_0={{common.password}}
        --prop:nsx_cli_passwd_0={{common.password}}
        --prop:nsx_hostname={{m3.name}}
        --prop:nsx_cli_audit_passwd_0={{common.password}}
        "{{common.image}}"
        vi://"administrator@rkc.local":"Nicira123$"@vc.rkc.local/Home/host/cluster67
      tags: mgr2

    - name: deploy nsx edge1
      command: ovftool
        --name={{e1.name}}
        --deploymentOption=large
        --X:injectOvfEnv 
        --X:logFile=ovftool.log 
        --allowExtraConfig 
        --datastore={{common.datastore}}
        --net:"Network 0=home_mgmt" 
        --net:"Network 1=Trunk" 
        --net:"Network 2=Trunk"  
        --net:"Network 3=Trunk"  
        --acceptAllEulas 
        --noSSLVerify 
        --diskMode=thin 
        --powerOn 
        --prop:nsx_ip_0={{e1.ip}} 
        --prop:nsx_netmask_0={{common.mask}} 
        --prop:nsx_gateway_0={{common.gw}} 
        --prop:nsx_dns1_0={{common.dns}}
        --prop:nsx_domain_0=rkc.local
        --prop:nsx_ntp_0={{common.ntp}}  
        --prop:nsx_isSSHEnabled=True 
        --prop:nsx_allowSSHRootLogin=True 
        --prop:nsx_passwd_0={{common.password}} 
        --prop:nsx_cli_passwd_0={{common.password}} 
        --prop:nsx_hostname={{e1.name}}
        "{{common.edgeimage}}"
        vi://"administrator@rkc.local":"Nicira123$"@vc.rkc.local/Home/host/cluster67
      tags: edge

    - name: deploy nsx edge2
      command: ovftool
        --name={{e2.name}}
        --deploymentOption=large
        --X:injectOvfEnv 
        --X:logFile=ovftool.log 
        --allowExtraConfig 
        --datastore={{common.datastore}}
        --net:"Network 0=home_mgmt" 
        --net:"Network 1=Trunk" 
        --net:"Network 2=Trunk"  
        --net:"Network 3=Trunk"  
        --acceptAllEulas 
        --noSSLVerify 
        --diskMode=thin 
        --powerOn 
        --prop:nsx_ip_0={{e2.ip}} 
        --prop:nsx_netmask_0={{common.mask}} 
        --prop:nsx_gateway_0={{common.gw}} 
        --prop:nsx_dns1_0={{common.dns}}
        --prop:nsx_domain_0=rkc.local
        --prop:nsx_ntp_0={{common.ntp}}  
        --prop:nsx_isSSHEnabled=True 
        --prop:nsx_allowSSHRootLogin=True 
        --prop:nsx_passwd_0={{common.password}} 
        --prop:nsx_cli_passwd_0={{common.password}} 
        --prop:nsx_hostname={{e2.name}}
        "{{common.edgeimage}}"
        vi://"administrator@rkc.local":"Nicira123$"@vc.rkc.local/Home/host/cluster67
      tags: edge
