---
- hosts: tool
  tasks: 
  - name: apt-get update 
    apt:
      update_cache: yes

  - name: addn ansible repository 
    apt_repository:
      repo: ppa:ansible/ansible
      state: present

  - name: upgrade linux header for trex 2.5.3
    raw: apt-get install linux-headers-`uname -r`

  - name: install pre-request packages 
    apt:
      name: "{{packages}}"
    vars:
      packages:
        - nfs-common
        - iperf 
        - git 
        - python-requests
        - ipython
        - open-vm-tools
        - ssh-askpass
        - software-properties-common
        - build-essential
        - ansible
      tags: pkg

  - name: git clone nsxt_validate 
    git: 
      repo: https://github.com/rickchen918/nsxt_validate.git
      dest: ~/nsxt_validate

  - name: git clone lab_build 
    git: 
      repo: https://github.com/rickchen918/lab_builder.git
      dest: ~/lab_builder

  - name: make trex use folder 
    file: 
      path: ~/trex
      state: directory

  - name: download trex packages and unarchive file
    unarchive:
      src: http://trex-tgn.cisco.com/trex/release/v2.53.tar.gz
      dest: ~/trex
      remote_src: yes

  - name: download terraform package 
    get_url: 
      url: https://releases.hashicorp.com/terraform/0.11.13/terraform_0.11.13_linux_amd64.zip
      dest: ~/terraform 

